### PR TITLE
Make ParameterBuilder methods public

### LINKED ISSUE #102: Make ParameterBuilder methods public
Currently builder methods of ParameterBuilder are all private which makes this class useless.

### PR DESCRIPTION
**Pull request by sergiychernov**
fixes #102

### CODE REVIEW

**Comment by sergiychernov** [comment]
@yahehe would be nice to have this available via new NuGet package. Thanks

**Comment by yahehe** [comment]
Alright, new version (2.2.11-alpha) has been pushed to nuget

**Comment by sergiychernov** [comment]
@yahehe thanks! However, dependency on Swagger.ObjectModel is not set correctly. It says Swagger.ObjectModel (>= 2.2.11) but only 2.2.11-alpha is available.
Could you please verify? 

Thanks,
Sergiy

**Comment by jnallard** [comment]
Yeah, that's my bad. 
I'll fix it!

**Comment by yahehe** [comment]
2.2.12-alpha should work for you @sergiychernov

**Comment by sergiychernov** [comment]
It works! Thanks, @yahehe, @jnallard

**Pull request merged**
