### PR TITLE
Fix xunit warnings and add some tests

### PR DESCRIPTION
**Pull request by catcherwong**
For this PR I have done the following works 

1. Fix xunit warnings after upgrading to version **2.3.0** 
2. Add some new tests for **Swagger.ObjectModel** 
3. ApiKeySecuritySchemeBuilder should return a new SecurityScheme object with **Description**

### CODE REVIEW

**Comment by yahehe** [comment]
Uh you have some weird merge commit at the beginning of this. Can you please rebase your changes off master?

**Comment by catcherwong** [comment]
@yahehe  Do you mean this class [ApiKeySecuritySchemeBuilder](https://github.com/yahehe/Nancy.Swagger/blob/master/src/Swagger.ObjectModel/Builders/ApiKeySecuritySchemeBuilder.cs) ?

**Comment by yahehe** [comment]
I mean this commit that somehow made it into your pull reuqest: https://github.com/yahehe/Nancy.Swagger/pull/140/commits/ac915cbf74e0a85a59b14f4f418caef09f724151

**Comment by catcherwong** [comment]
All right , I understand it ! I will rebase at first !

**Pull request closed without merging**
